[package]
name = "sqllogictest"
version = "0.1.0"
edition = "2021"
description = "Sqllogictest parser and runner."
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/singularity-data/sqllogictest-rs"
repository = "https://github.com/singularity-data/sqllogictest-rs"
keywords = ["sql", "database", "parser"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10"
log = "0.4"
tempfile = "3"
thiserror = "1"
async-trait = "0.1.41"
postgres = "0.19"
structopt = "0.3"
libtest-mimic = "0.3"
glob = "0.3"
