[package]
name = "sqllogictest"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Sqllogictest parser and runner."

[dependencies]
async-trait = "0.1"
derivative = "2.2.0"
difference = "2.0"
glob = "0.3"
humantime = "2"
itertools = "0.10"
tracing = "0.1"
tempfile = "3"
thiserror = "1"
futures = "0.3"
libtest-mimic = "0.6"
regex = "1.7.0"
owo-colors = "3.5.0"
md5 = "0.7.0"
fs-err = "2.9.0"
